name: Buf Push
on: # Apply to all pushes to `main`
  push:
    branches:
      - main
jobs:
  push-to-bsr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
